ДЗ второго занятия решены
js-tasks-ru/vue-20201022_oleg-chabak pull request #2
Opened 2020-10-28 20:12 UTC by olegchabak

2020-10-28 22:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-29 07:00 UTC, ShGKme requested changes
Задача CounterButton принята.
В задаче MeetupPageDraft требуется исправить проблему безопасности -- XSS

2020-10-29 07:00 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <h5 class="meetup-agenda__title" v-html="item.title || getAgendaTitle(item.type)"></h5>
v-html выведет значение как html без какого-либо экранирования. Это потенциальный XSS.

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С v-html получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

Если так было сделано из-за `<s>` в названии одного из докладов, то это оригинальное название: [https://vueconf.us/schedule/](https://vueconf.us/schedule/). `All you need is <s>love</s> Apollo Client`

Но наличие таких названий не должно приводить к XSS

2020-10-29 07:00 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <img class="icon" alt="icon" :src="`/assets/icons/icon-${getAgendaIcon(item.type)}.svg`"/>
Лучше избегать вызова методов в шаблоне.
Здесь может быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут перевычисляться  только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кешируется.

Кроме того, это не декларативно. Нам требуется описать шаблон, который декларирует, описывает, какое отображение (HTML) мы хотим получить. А вызов местода - это императивный путь, мы говорим, что нужно сделать, чтобы получить данные, необходимые для формирования страницы.

2020-10-29 07:00 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +    meetup: {},
На вебинаре мы начальным значением массива устанавливали пустой массив. Это корректно, пустой массив митапов - это частный случай массива митапов. Но пустой объект - не частный случай объекта с описанием митапа. Хотя установка начального значения в `{}` избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать `nul`l и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

2020-11-15 17:29 UTC, ShGKme commented
Нужна ли помощь с решением задачи?

2020-11-17 19:54 UTC, olegchabak commented
> Нужна ли помощь с решением задачи?

Запушил правки по задаче 02-MeetupPageDraft

2020-11-17 20:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-17 23:07 UTC, ShGKme approved these changes
Принято 👍

2020-11-17 23:07 UTC, merged